name: great_sky_gru
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - torchvision
  - torchaudio
  - numpy
  - matplotlib
  - tqdm
  - pip
  - pip:
    - torchmetrics